ingress:
  enabled: true
  host: ""
  visibility: public

security:
  profile: restricted

scaling:
  enabled: true

config:
  appEnv: dev
  appMessage: "Hello from dev"
  readinessDelaySeconds: "5"
  requireMessage: "true"