deployment:
  replicas: 3

image:
  repository: platform-engineering-aws-ecr
  registry: 319895613301.dkr.ecr.eu-west-1.amazonaws.com
  tag: "specified"
  pullPolicy: IfNotPresent

workloadProfile: important

ingress:
  enabled: true

env:
  - name: APP_ENV
    value: prod