nameOverride: ""
fullnameOverride: ""

deployment:
  replicas: 1

image:
  repository: platform-engineering-aws-ecr
  registry: 319895613301.dkr.ecr.eu-west-1.amazonaws.com
  tag: "latest"
  pullPolicy: IfNotPresent

application:
  port: 5000
  probes:
    startupPath: /livez
    livenessPath: /livez
    readinessPath: /readyz

# visibility defines wether app is reachable from the internet
# internal   = not reachable
# public = reachable
ingress:
  enabled: false
  host: ""
  path: /
  visibility: internal

security:
  profile: restricted

# workloadProfile defines standard resource sizing
# general   = small workloads
# important = medium workloads
# critical  = high-priority workloads
#
# Most services should use workloadProfile.
# Use 'resources' only if you need fine-grained control.
workloadProfile: general
# optional override
resources: {}

# profile defines horizontal auto-scaling behavior
# conservative   = slower scale up, slower scale down
# standard = moderate scale up, moderate scale down
# aggressive  = fast scale up, fast scale down
#
# Most apps should use standard.
# Use 'conservative' for apps that do not expect too many changes
# Use 'aggressive' for lightweight apps which needs fast response rate
scaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilization: 70
  profile: standard

# profile defines pod disruption budget behavior
# none     = there are no minimun number of pods 
# standard = sets minimun number of pods available to a minimun number
# critical = sets minimun number of pods available to a high number 
#
# Most apps should use standard.
# Use 'conservative' for apps that do not expect too many changes
# Use 'aggressive' for lightweight apps which needs fast response rate
availability:
  profile: standard

config:
  appEnv: default
  appMessage: "Hello from Platform Engineering Project"
  readinessDelaySeconds: "0"
  requireMessage: "false"
  enableStressEndpoint: "false"