apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  APP_MESSAGE: {{ .Values.config.appMessage | quote }}
  READINESS_DELAY_SECONDS: {{ .Values.config.readinessDelaySeconds | quote }}
  REQUIRE_MESSAGE: {{ .Values.config.requireMessage | quote }}