apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-app
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: sample-app
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.application.port }}
          protocol: TCP
        env:
          {{- toYaml .Values.env | nindent 12 }}
        {{- if eq .Values.workloadProfile "critical" }}
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        {{- else if eq .Values.workloadProfile "important" }}
        resources:
          requests:
            cpu: 200m
            memory: 192Mi
          limits:
            cpu: 400m
            memory: 384Mi
        {{- else }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        {{- end }}
        livenessProbe:
          httpGet:
            path: {{ .Values.application.healthPath }}
            port: {{ .Values.application.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.application.healthPath }}
            port: {{ .Values.application.port }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3