name: CD - Prod

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Immutable image tag to deploy (example: sha-d93529a)"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  RELEASE_NAME: ${{ vars.RELEASE_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_EKS_ROLE_ARN: ${{ vars.AWS_EKS_ROLE_ARN }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  CHART_PATH: ${{ vars.CHART_PATH }}
  K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}

concurrency:
  group: cd-prod
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_EKS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Deploy with Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $K8S_NAMESPACE \
            --create-namespace \
            -f k8s/values/sample-app/prod.yaml \
            --set image.tag=${{ github.event.inputs.image_tag }}

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/$RELEASE_NAME -n $K8S_NAMESPACE --timeout=180s
          kubectl get pods -n $K8S_NAMESPACE
          kubectl get svc -n $K8S_NAMESPACE